### ISSUE TITLE
KeyError: 'input_type'

### ISSUE THREAD

**Issue by lauriaco** [SwolfPy-Project/swolfpy#12]
Hi, I was trying to follow along with the case study example ([https://github.com/SwolfPy-Project/CaseStudy-JIE2021/blob/main/Base%20Case/Base_Case.ipynb]) to try and better understand the model and am encountering a KeyError when trying to create the project - full .md export attached.

Could you help me understand what/why this error is being thrown and how I can fix it? Thank you!

[CaseStudySwolfpy_20230822.md](https://github.com/SwolfPy-Project/swolfpy/files/12413070/CaseStudySwolfpy_20230822.md) 

( @msm-sardar )

**Comment by lauriaco** [comment]
PDF export attached here: [CaseStudySwolfpy_20230822.pdf](https://github.com/SwolfPy-Project/swolfpy/files/12413222/CaseStudySwolfpy_20230822.pdf)

**Comment by msm-sardar** [comment]
You have a typo! `input_tpye` -> `input_type`

![image](https://github.com/SwolfPy-Project/swolfpy/assets/68316163/b41f07b5-1182-4b8f-b3d9-b2f50db42382)
