### ISSUE TITLE
Graphviz Problem in Optimization cases 1,2 and 3.

### ISSUE THREAD

**Issue by mert21433** [SwolfPy-Project/swolfpy#4]
Hello,

I am having this issue,
![image](https://user-images.githubusercontent.com/67761900/145882697-a334af96-3b97-4fcd-838f-55c9228dbd8a.png)
This is the image of installed packages:
![image](https://user-images.githubusercontent.com/67761900/145883147-8eb1da13-3c73-44b7-9184-b47b7bb00cf4.png)
This is the image of not installed packages:
![image](https://user-images.githubusercontent.com/67761900/145883218-bae6a85e-21fd-4570-b698-337c6ce6361b.png)
I can provide additional information if needed,

Thank you.

**Comment by msm-sardar** [comment]
Hey Mert,

In anaconda prompt, activate the swolfpy environment and do the following:

```
pip list
```

Check the list to see whether you have **networkx** installed or not. If not, install it and check again.

```
pip install networkx
```
Let me know the result.

**Comment by mert21433** [comment]
![image](https://user-images.githubusercontent.com/67761900/146223835-25b1b42f-6f08-49ae-a25c-e0f73e41eec0.png)
I have this pop-up. It seems I already had it.
Also, 
I tried to start the GUI, but I had this warning;
![image](https://user-images.githubusercontent.com/67761900/146224014-0a8226e7-6c51-4b4a-a4fb-01667919161d.png)
I thought maybe these could be related.
Should I reinstall and try the swolfpy and try the networkx again?
Thank you.

**Comment by msm-sardar** [comment]
@mert21433 send the results of  ``pip list``, let's see what packages/versions you have.

it would be easier to reinstall.

Does the graphviz work when you use the interface or create a base case (https://github.com/SwolfPy-Project/CaseStudy-JIE2021/blob/main/Base%20Case/Base_Case.ipynb)?

**Comment by mert21433** [comment]
1- Here is the pip list.
[pip_list.txt](https://github.com/SwolfPy-Project/swolfpy/files/7721108/pip_list.txt)
2- I am going to write results when I reinstall and get the GUI working.
3- The graphviz error I got was from the optimization part of the base case.

Other than this, base cases are working, as in they give the results.

**Comment by msm-sardar** [comment]
@mert21433  First activate the swolfpy environment ``conda activate swolfpy``  and then ``pip list``

**Comment by mert21433** [comment]
Here it is.
[pip_list.txt](https://github.com/SwolfPy-Project/swolfpy/files/7721223/pip_list.txt)

**Comment by msm-sardar** [comment]
@mert21433  You don't have **networkx** in swolfpy environment. Do the following:
```
conda activate swolfpy
pip install networkx
```

**Comment by mert21433** [comment]
This is the result,
![image](https://user-images.githubusercontent.com/67761900/146271794-d814a265-2ce1-4bd5-bde8-47e36ec4cb20.png)
 And this is the most recent pip list, networkx is there.
[pip_list.txt](https://github.com/SwolfPy-Project/swolfpy/files/7722975/pip_list.txt)

I can also give an update after the reinstallation.

**Comment by mert21433** [comment]
This is the result when I try to reinstall with python version 3.7. But it worked with 3.8. Is using 3.8 going to be a problem?
![image](https://user-images.githubusercontent.com/67761900/147391854-971097b0-767e-49d2-9d89-e862e42ddb78.png)

Thanks!

**Comment by msm-sardar** [comment]
@mert21433 I couldn't reproduce your error with Graphviz!

Why do you need python 3.8? The error is not related to SwolfPy, it's related to bw2. I suggest using the default version (python 3.7) or checking this issue (https://github.com/brightway-lca/brightway2-io/issues/90).

**Comment by mert21433** [comment]
Which specific bw2data version solves this problem? 
I have installed 3.6 but received a warning saying that swolfpy 0.2.4 requires the 
3.6.2 version.
(FYI, so far, using python 3.8 is the only way I can start the GUI)

**Comment by mert21433** [comment]
> @mert21433 I couldn't reproduce your error with Graphviz!
> 
> Why do you need python 3.8? The error is not related to SwolfPy, it's related to bw2. I suggest using the default version (python 3.7) or checking this issue ([brightway-lca/brightway2-io#90](https://github.com/brightway-lca/brightway2-io/issues/90)).
